### ISSUE TITLE
Requirements for environment installation

### ISSUE THREAD

**Issue by mJones00** [korrawe/harp#2]
Hello,

There were some issues when setting up the environment for the repo. First, the requirements.txt file mentions that the pytorch3d version used is 0.5.0 but in renderer_helper there is an import of ShaderBase from pytorch3d.renderer.mesh.shader which was introduced in version 0.6.2 if I'm not mistaken.

Anyway, here are the steps I used to create the environment, they might be useful:

- create a conda env with python 3.9:
`conda create -n harp python=3.9 && conda activate harp`
- install requirements for pytorch3d version 0.6.2, it is possible to use different versions of pytorch, cudatoolkit by checking out the other compatible versions in the package name located in [https://anaconda.org/pytorch3d/pytorch3d/files?version=0.6.2&page=1&channel=main]() , then install following [https://pytorch.org/get-started/previous-versions/]() :
`conda install pytorch==1.11.0 torchvision==0.12.0 cudatoolkit=11.3 -c pytorch`
- some other requirements according to official instructions from [https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md]():
`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`
- install pytorch3d version 0.6.2:
`conda install pytorch3d=0.6.2 -c pytorch3d`
- I traced the actual requirements for the repo, you can put them in a `requirements_reduced.txt` and install with `pip install -r requirements_reduce.txt`:
```
tensorboard
lpips
pytorch_msssim
chumpy # then comment "#from numpy import bool, int, float, complex, object, unicode, str, nan, inf "in /home/xx/moniconda3/envs/harp/lib/python3.9/site-packages/chumpy/__init__.py
scikit-learn
scipy
matplotlib
scikit-image 
matplotlib 
imageio 
plotly 
opencv-python
```

**Comment by korrawe** [comment]
Thank you so much for checking and providing clear instructions!
The version of pytorch3D is indeed wrong as I push the previous requrements.txt instead of the most recent one.
I now updated the readme following your suggestion.
